In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array([['Red'], ['Blue'], ['Green'], ['Blue']])

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(data)

print(encoded)
print("Feature Names:", encoder.get_feature_names_out())


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Feature Names: ['x0_Blue' 'x0_Green' 'x0_Red']


In [2]:
sentence = "I love Data Science"
words = sentence.split()

vocab = sorted(set(words))
print("Vocabulary:", vocab)

one_hot = {word: [1 if w == word else 0 for w in vocab] for word in vocab}

for word, vec in one_hot.items():
    print(f"{word}: {vec}")

Vocabulary: ['Data', 'I', 'Science', 'love']
Data: [1, 0, 0, 0]
I: [0, 1, 0, 0]
Science: [0, 0, 1, 0]
love: [0, 0, 0, 1]
